### ISSUE TITLE
Google Play Services has stopped

### ISSUE THREAD

**Issue by Brouilles** [MrStahlfelge/gdx-gamesvcs#20]
Hi, 
First thanks for your very good jobs about gdx-gamesvcs!
I need to implement Google Play Services in my libgdx project but, i have an error. When the user click on the button, the Google UI appear with animation and when the loading show up i have a popup with this error "Google Play Services has stopped" and after "the application is having problems ...". After this, the app return always `isConnectionPending() equal true`. 

I saw your code example here https://github.com/MrStahlfelge/gdx-gamesvcs-app/blob/feature/gpgs/core/src/de/golfgl/gdxgamesvcsapp/GdxGameSvcsApp.java, and my code it almost the same (just, in AndroidLauncher i don't have mapToGsId and @override things because GpgsMappers doesn't exist in the last version of gdx-gamesvcs). 

So, of course, i watched on the Google Play Console my configuration. But, i don't know where I could have a configuration problem. My app is in Beta only and i ticked in the game service configuration "allow Alpha & Beta users". I tested with release signed apk and link (associated application) my service with my app in Play Console and app_id is defined. I don't understand ... 

The problem is present on all devices that have the game.
You have an idea?

Thank you for your answer, have a nice day.

**Comment by MrStahlfelge** [comment]
If the _Play services_ are crashing and not _your game_, you probably did everything right.

I also had this problem once, and it was solved the next day by doing nothing, so I guess it was some kind of caching problem the Play services had.

Does my game Falling Lightblocks (install from the Play Store) works with GPGS on your test devices?

**Comment by Brouilles** [comment]
Hi, 
Thanks for your awnser!
You have maybe right, I will wait a few days to see and if not I would advise re-create an entire project on Google Play and code for make more test.

But your game run perfectly, Falling Lightblocks, so maybe a caching problem. I'll let you know about the progress.

**Comment by Brouilles** [comment]
Hi, 
The problem persist, so I will not do the integration of the google service in my game. 
Thank you for your reply.

**Comment by MrStahlfelge** [comment]
Sorry to hear that. Then I will close this issue.
