### ISSUE TITLE
GPGS Real-time Multiplayer support

### ISSUE THREAD

**Issue by SohnyBohny** [MrStahlfelge/gdx-gamesvcs#28]
Is there any support for [Real-time Multiplayer](https://developers.google.com/games/services/common/concepts/realtimeMultiplayer)?

**Comment by MrStahlfelge** [comment]
I use real-time multiplayer in my game with this lib, but there is no way to use my code for other games: it is too specific. So everyone must come up with an own solution.

The lib supports building an own extension: `mGoogleApiClient` is not private, but protected. This way your own subclass can use or expose it to your multiplayer code.
