### ISSUE TITLE
GPGS Android: UserRecoverableAuthException: NeedPermission

### ISSUE THREAD

**Issue by PromanSEW** [MrStahlfelge/gdx-gamesvcs#33]
I configured my app by Wiki and Google Play Services sdocumentation, but I cannot to sign in
I get the following message in logcat:
```
W/GamesAuthenticator: Failed to sign in silently
    com.google.android.gms.auth.UserRecoverableAuthException: NeedPermission
```
How to fix this error?

**Comment by MrStahlfelge** [comment]
Do you give your players a way to explicitly sign in?

https://github.com/MrStahlfelge/gdx-gamesvcs/wiki/Google-Play-Games#explicit-sign-in-and-sign-out

**Comment by PromanSEW** [comment]
I use explicit method `logIn()` by clicking the button

**Comment by PromanSEW** [comment]
I tested Honor Play, request permission was shown, and login is successful. But on Samsung Galaxy S10e (Android 10) I have this error, and permission request is not showing

**Comment by MrStahlfelge** [comment]
That's the normal flow. GpgsClient shows the login request dialog if the silent login fails, but only if you called `logIn()`. As you do so, please check logcat or via debugger from this line on why the log in does not work:

https://github.com/MrStahlfelge/gdx-gamesvcs/blob/57c6eaa8e3bc5be46f9248cf16b20a49b43863ce/android-gpgs/src/de/golfgl/gdxgamesvcs/GpgsClient.java#L267

The Google Play Games app is installed on the S10?

**Comment by PromanSEW** [comment]
> The Google Play Games app is installed on the S10?
Yes

**Comment by PromanSEW** [comment]
@MrStahlfelge I provided logs

**Comment by MrStahlfelge** [comment]
I can't see anything in the logs, so best is if you check with the debugger
Is the account on the S10 the same as on the other phone? Most sign in problems are caused by not adding certain accounts to beta test with unpublished GPGS projects.

**Comment by PromanSEW** [comment]
Both accounts are added

**Comment by MrStahlfelge** [comment]
Did you try if any other game can sign in on the device?

**Comment by PromanSEW** [comment]
Other games work fine

**Comment by MrStahlfelge** [comment]
Sorry, can't give you further assistance here. I doubt that it is a problem with the lib, so you should ask in general Android/GPGS help channels.
