### ISSUE TITLE
Google Play Games no achievement popup

### ISSUE THREAD

**Issue by MichalLebeda** [MrStahlfelge/gdx-gamesvcs#34]
Achievement popups are not shown. It may be related to [this](https://www.badlogicgames.com/forum/viewtopic.php?f=11&t=27559)

**Comment by MrStahlfelge** [comment]
It worked in the past, I'll check if the behaviour was changed.

**Comment by MichalLebeda** [comment]
I haven't managed to fix this even with tips I have found on the internet (adding parameters to Builder). 
`        
gdxVersion = '1.9.10'  
gamesvcsVersion = '1.0.1'
`

**Comment by MrStahlfelge** [comment]
Tested, popup still comes up for me

**Comment by MichalLebeda** [comment]
I have tried to build [demo app](https://github.com/MrStahlfelge/gdx-gamesvcs-app) but I cannot sign in ( even though I have changed package name and replaced all of the ids). If build that demo app for test, did you build it using the latest version of this lib? I am asking because your demo app uses 0.2.5 SNAPSHOT. It is really a strange issue :(

**Comment by MrStahlfelge** [comment]
Yes, I used the latest version.
You won't be able to sign in with the demo app, you need to create your own gpgs project and link it to your signing signature.

**Comment by MichalLebeda** [comment]
I have actually used my games project from another game and signed it with the same certificate

**Comment by MichalLebeda** [comment]
Still no luck, replicated manifest and other relevant things from demo app to my game. I wonder if it isn't phone related. Is it possible to upload your release signed demo app so I can try? Thanks for this lib btw, helped me a lot but this doesn't work for some reason.

**Comment by MrStahlfelge** [comment]
You can use my release signed game for testing: https://github.com/MrStahlfelge/gdx-gamesvcs#working-demos

**Comment by MichalLebeda** [comment]
I have mannaged to fix it! The **problem was that the achievements didn't have any icons**!! Even google tells us that it is ok to not have icons if it is in testing stage 😠😠😠. What about adding some warning somewhere (wiki?) ? It could save me 2 days of work and searching

**Comment by MrStahlfelge** [comment]
That's great news. You should add an answer to the #1 question on SO: https://stackoverflow.com/questions/26474718/google-play-games-achievement-unlocked-popup-not-showing
