### ISSUE TITLE
wiki update

### ISSUE THREAD

**Issue by julienvillegas** [MrStahlfelge/gdx-gamesvcs#44]
not an issue, really, but a minor edit as I went through the configuration of this awesome library:

in this wiki page: https://github.com/MrStahlfelge/gdx-gamesvcs

For core in the build.gradle, instead of :
compile "de.golfgl.gdxgamesvcs:gdx-gamesvcs-core:$gamesvcsVersion"
I used
api "de.golfgl.gdxgamesvcs:gdx-gamesvcs-core:$gamesvcsVersion"
(compile was showing "obsolete")

same thing for for iOS, in this page:  https://github.com/MrStahlfelge/gdx-gamesvcs/wiki/Apple-Game-Center

but for Android, I used "implementation" instead of API.

I used LibGDX 1.10.0

**Comment by MrStahlfelge** [comment]
Thanks for the hint, it's been quite some time since I wrote the docs. Will change the next days.

**Comment by MrStahlfelge** [comment]
Updated the pages of the still active components, please check.
