### ISSUE TITLE
Documentation has incorrect version label

### ISSUE THREAD

**Issue by JojoIce** [MrStahlfelge/gdx-gamesvcs#49]
In the Apple Game Center the documentation states:

implementation "de.golfgl.gdxgamesvcs:gdx-gamesvcs-ios-gamecenter:$gamsvcsVersion"

and in the main doc it states:

gamesvcsVersion = '1.1.0'

It took me a bit too long time to realize that there is a missing 'e' in the first line. Anyone following in my footsteps will probably save some time of those strings match.

**Comment by MrStahlfelge** [comment]
Thanks for pointing out, I've fixed it.
