### ISSUE TITLE
GPGS end of support for some features

### ISSUE THREAD

**Issue by mgsx-dev** [MrStahlfelge/gdx-gamesvcs#5]
As stated here : https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html GPGS will end support for Gift, Quests and Requests.

Current API define a submitEvent feature which is if I'm right related to quests for GPGS implementation.

Since other services provide events, you could add a feature query like "idEventSupported" ?

For this reason, I won't implement the submitEvent method in the desktop implementation.

What do you think ?

**Comment by MrStahlfelge** [comment]
Events and quests are indeed related: events are a premise for quests. But they are also a premise for analytics, which they state are widely used. On [the events and quests page](https://developers.google.com/games/services/common/concepts/quests), they just noted to discontinue quests so I think events are not concerned by discontinuation.

Regarding the other game services: there are services that do not support events (GameCircle does not). The implementations just do nothing in this case. Feature query is of course no problem when I adapt your isFeatureSupported() method.

**Comment by MrStahlfelge** [comment]
isFeatureSupported() is added to core module, also a GameServiceFeature SubmitEvents
