### ISSUE TITLE
ERROR while show leaderboards 

### ISSUE THREAD

**Issue by hdls19** [MrStahlfelge/gdx-gamesvcs#50]
Hi

First, thanks for the your work

I'm using your library in my game and getting an error when I call the **gsClient.showLeaderboards()** method

![image](https://user-images.githubusercontent.com/41329018/164938518-cfe0f5f2-6d7e-4835-afa8-c12dfd1ada47.png)

The code i am using in AndroidLauncher:

```
public class AndroidLauncher extends AndroidApplication {

	private GpgsClient gpgsClient;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);

		AsteroidBustersXGame game = new AsteroidBustersXGame();

		this.gpgsClient = new GpgsClient()
				.setGpgsLeaderboardIdMapper(new IGameServiceIdMapper<String>() {

					@Override
					public String mapToGsId(String independantId) {
						return GpgsMappers.mapToGpgsLeaderboard(independantId);
					}
				})
				.initialize(this, false);
		game.gsClient = gpgsClient;

		AndroidApplicationConfiguration config = new AndroidApplicationConfiguration();
		config.useAccelerometer = false;
		config.useCompass = false;
		config.useImmersiveMode = true;
		initialize(game, config);
	}
}
```
Main Game Class **create()** method:
```
if (gsClient == null) {
	Gdx.app.log("GS_CLIENT", "GsClient is null");
	gsClient = new MockGameServiceClient(1) {
		@Override
		protected Array<ILeaderBoardEntry> getLeaderboardEntries() {
			return null;
		}

		@Override
		protected Array<String> getGameStates() {
			return null;
		}

		@Override
		protected byte[] getGameState() {
			return new byte[0];
		}

		@Override
		protected Array<IAchievement> getAchievements() {
			return null;
		}

		@Override
		protected String getPlayerName() {
			return null;
		}
	};
}

Gdx.app.log("GS_CLIENT", "GsClient set listener");
gsClient.setListener(this);

//My game initialization

Gdx.app.log("GS_CLIENT", "GsClient resume session");
gsClient.resumeSession();
```
Where I call **showLeaderboards()** method:
```
highscoresButton = new ImageButton(highscoresStyle);
highscoresButton.addListener(new ClickListener() {

    @Override
    public void clicked(InputEvent event, float x, float y) {
        try {
            game.gsClient.showLeaderboards(LEADERBOARD1);
        }
        catch (GameServiceException e) {
            Gdx.app.error("GS_CLIENT", "Failed to show leaderboards", e);
        }
    }
});
```
GpgsMappers class:
```
public class GpgsMappers {

    public static String mapToGpgsLeaderboard(String leaderboardId) {
        String gpgsId = null;

        if (leaderboardId != null) {
            if (leaderboardId.equals(AsteroidBustersXGame.LEADERBOARD1))
                gpgsId = "CgkIjOjVy8gdEAIQAQ";
        }

        return gpgsId;
    }
}
```

I also have a version of gdx 1.10.0, in the example its - 1.9.8. Most likely the problem is somewhere else.

Authorization passes - a welcome gpgs popup window appears with my username, but when click 'Highscores' it's load gpgs highscores page, but loading is freezing

Thanks in advance

**Comment by hdls19** [comment]
I also get error when call **fetchLeaderboardEntries()** method: 
![image](https://user-images.githubusercontent.com/41329018/164967090-fc1a5741-d67a-4b40-bd55-56076cf2410a.png)

**Comment by MrStahlfelge** [comment]
You will get this error on every call. You need to do what the error tells you: link your app in the Play Games dev console.

**Comment by hdls19** [comment]
I have already registered metadata app_id in AndroidManifest.xml
![image](https://user-images.githubusercontent.com/41329018/164971011-02d4cda6-4450-4856-b645-ccb75a960c3d.png)

which matches with OAuth 2.0 Client IDs on Google Cloud Platform
![image](https://user-images.githubusercontent.com/41329018/164971098-ba51f1fd-784b-4907-b2cf-b80351345c09.png)

Please tell me what else should I do?

**Comment by MrStahlfelge** [comment]
Google Play Games is different to set up. https://developers.google.com/games/services/console/enabling

**Comment by hdls19** [comment]
I found out what the reason was - in my console in **Play Games Services > Setup and Management > Configuration** was only 1 credentials for release. When add debug credentials - then everything worked
