### ISSUE TITLE
loadGameState and saveGameState need designated callback interfaces

### ISSUE THREAD

**Issue by MrStahlfelge** [MrStahlfelge/gdx-gamesvcs#6]
If loadGameState is performed, the loaded game state response comes back on the main game service listener's gsGameStateLoaded(byte[] gameState) method.

This does not fit in any case: If several game states are used, and if the cloud sync feature is not used at all the method declaration is not necessary.

The method should be moved to an own interface and the response listener should be paramatrized on the loadGameState call. 

Also, saveGameState should get a callback interface for returning if operation was performed and if it was successful.

**Comment by mgsx-dev** [comment]
Fully agree with all this ;-)
