### ISSUE TITLE
obsolete feature

### ISSUE THREAD

**Issue by mgsx-dev** [MrStahlfelge/gdx-gamesvcs#7]
https://github.com/MrStahlfelge/gdx-gamesvcs/blob/eb7b388586b6f818d333d85293a6dc96e2a52eef/core/src/de/golfgl/gdxgamesvcs/IGameServiceClient.java#L251

Obsolete since showGameStates was removed

**Comment by MrStahlfelge** [comment]
That's right. I removed showGameStates because its parameters were not sufficient. Unlike the other show* method, it needs response listeners. Could also be that you need different methods for saving and loading.

So I better remove the ShowGameStatesUI, too.
