### ISSUE TITLE
GPGS Desktop: Support submitting events

### ISSUE THREAD

**Issue by MrStahlfelge** [MrStahlfelge/gdx-gamesvcs#9]
GPGS desktop does not support submitting events in current state.

**Comment by mgsx-dev** [comment]
ok I will look at it when i have time but it definitely worth it.

**Comment by MrStahlfelge** [comment]
Set the reference accidently ;)

**Comment by MrStahlfelge** [comment]
The API method for submitting events is not well documented by Google, but the implementation in GPGS-HTML shows how to use it.

**Comment by MrStahlfelge** [comment]
Closing this as desktop is not supported by Google any more.
